name: Go

on: push 

jobs:

  build:
    env:
      GO111MODULE: on
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
          go get -u golang.org/x/lint/golint
          export golint=$(go list -f {{.Target}} golang.org/x/lint/golint)
          go mod vendor

    - name: Test
      run: |
          golint .
          go test -v ./... --bench=. -cover
